# Generated by Django 5.0.3 on 2025-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=255)),
                ('creatorName', models.CharField(max_length=255)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('estimatedTime', models.IntegerField()),
                ('directions', models.TextField()),
            ],
        ),
    ]
